TString device_name[] = {"reg_asym_atl1",
			"reg_asym_atl2",
			"reg_asym_atr1",
			"reg_asym_atr2",
			"reg_asym_usl",
			"reg_asym_usr",
			"reg_asym_atl_dd",
			"reg_asym_atl_avg",
			"reg_asym_atl1_reg_asym_usl_dd",
			"reg_asym_atl2_reg_asym_usl_dd",
			"reg_asym_atl_avg_reg_asym_usl_dd",
			"reg_asym_atr_dd",
			"reg_asym_atr_avg",
			"reg_asym_atr1_reg_asym_usr_dd",
			"reg_asym_atr2_reg_asym_usr_dd",
			"reg_asym_atr_avg_reg_asym_usr_dd"};
