TString device_list[] = {"reg_asym_atl1",
			"reg_asym_atl2",
			"reg_asym_atr1",
			"reg_asym_atr2",
			"reg_asym_usl",
			"reg_asym_usr",
			"reg_asym_atl_dd",
			"reg_asym_atl_avg",
			"reg_asym_atl1-reg_asym_usl",
			"reg_asym_atl2-reg_asym_usl",
			"reg_asym_atl_avg-reg_asym_usl",
			"reg_asym_atr_dd",
			"reg_asym_atr_avg",
			"reg_asym_atr1-reg_asym_usr",
			"reg_asym_atr2-reg_asym_usr",
			"reg_asym_atr_avg-reg_asym_usr"};
